### PR TITLE
Different updates for web-interface

### PR DESCRIPTION
**Pull request by benjaminfuchs**
- [x] serve jquery from local filesystem (web should work even with no internet access)
- [x] Server->webbrowser: pull the complete settings to the browser, e.g. with path /get_settings. A
  necessary step would be to split Settings.save() into two parts (serialization to json and final
  dump to file). For the web we would reuse the first part and instead of dumping the json to the file
  the json-string would go to the response-stream.
- [x] Webbrowser->server: some JavaScript function would collect all data from the UI and post them to
  e.g. /save_settings. The  server part is a bit more tricky. The method would need to deserialize
  the settings and call Settings.set() for all attributes which did change (this is the tricky part I guess). 
- [x] Add feature to Enable/Disable alarm.
- [x] Add feature to show and edit days of week for alarm.
- [x] /get_sound_alarms to fill appropriate dropdowns in the UI

### CODE REVIEW

**Comment by bablokb** [comment]
Hi,
the last commit (Calling listeners...) breaks some things. I already had this code in Settings.py but removed it again, since in some cases re-setting a value should also trigger an action. An example is resetting a text (e.g. name of radio-station) will trigger the display regardless of the old state of _display.text.

You should move the comparison to the WebThread, since for these settings we actually want the given logic. 

Otherwise, the commits look fine.

**Comment by bablokb** [comment]
I just added two commits: added section [WEB] to /etc/nerd-alarmclock.conf with an additional attribute 'active' which I check in /usr/local/sbin/nerd-alarmclock.py. Looking at your code I assume you already have the section [WEB] in your local repository.

**Comment by benjaminfuchs** [comment]
Hi,
I rebased the branch to get the [WEB] section. Actually forgot to commit that. But looks good 👍 
As you recommended I moved the updating of the listeners into the WebThread.
Also wrote a little about page and added the icons to the repo.
Greetings,
Ben

**Review by bablokb — APPROVED** [review]
Hi, I think you can go on and merge the commits. I have a test-system and will run a test after the holidays. Have a nice time!

**Pull request merged**
